const products = [
  {
    _id: '1',
    name: 'eggs',
    image: '/images/eggs.jpg',
    description: 'Fresh day old eggs straight from the farm',
    category: 'gorceries',
    price: '1450',
    countInStock: 25,
    rating: 5,
    numReviews: 34,
  },
  {
    _id: '2',
    name: 'chicken',
    image: '/images/chicken.jpg',
    description: 'Fresh 2.5kg whole organic chickens',
    category: 'gorceries',
    price: '1800',
    countInStock: 25,
    rating: 5,
    numReviews: 24,
  },
  {
    _id: '3',
    name: 'garlic',
    image: '/images/garlic.jpg',
    description: 'fresh garlic from tunisia to make your meals pop',
    category: 'gorceries',
    price: '300',
    countInStock: 13,
    rating: 5,
    numReviews: 19,
  },
  {
    _id: '4',
    name: 'juice',
    image: '/images/juice.jpg',
    description:
      'Freshly squeezed orange juice hand picked with no additives or preservative',
    category: 'gorceries',
    price: '800',
    countInStock: 20,
    rating: 5,
    numReviews: 18,
  },
  {
    _id: '5',
    name: 'milk',
    image: '/images/milk.jpg',
    description: 'Fresh milk processed under the highest quality standards',
    category: 'gorceries',
    price: '1500',
    countInStock: 25,
    rating: 5,
    numReviews: 34,
  },
  {
    _id: '1',
    name: 'oil',
    image: '/images/oil.jpg',
    description: 'nutritios vegetable low fat oil for your tasty meals',
    category: 'gorceries',
    price: '1200',
    countInStock: 22,
    rating: 5,
    numReviews: 31,
  },
  {
    _id: '1',
    name: 'onions',
    image: '/images/onions.jpg',
    description: 'tasty red onions grown from the best farms',
    category: 'gorceries',
    price: '800',
    countInStock: 25,
    rating: 5,
    numReviews: 34,
  },
  {
    _id: '1',
    name: 'pepper',
    image: '/images/pepper.jpg',
    description: 'Fresh hot african pepper ',
    category: 'gorceries',
    price: '700',
    countInStock: 40,
    rating: 5,
    numReviews: 34,
  },
  {
    _id: '1',
    name: 'tomatoes',
    image: '/images/tomatoes.jpg',
    description: 'Fresh italian tomatoes habd picked for you',
    category: 'gorceries',
    price: '600',
    countInStock: 47,
    rating: 5,
    numReviews: 74,
  },
];

export default products;
